development:
  secret_key_base: 722cefb092a790d9d2aa1e138da174034441f6dcb408aeeea31865870fa07ee1a8e14b55dee157fc50b8501448b205a2e2ccb6da0608504f26cac110c2802846
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>

test:
  secret_key_base: 522af112a9919c2a1186b2ecd7e8de07b99cdc0b5624242e17bdc9dae06b7f4372a725172d58785a9a3428283fab61f5b970bf8864cca87c6fb592b40fa412d8

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>

ratanak_staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>

production_api:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_calendar_id: <%= ENV["GOOGLE_CALENDAR_ID"] %>
